<template>
  <div v-if="book" class="flex w-full space-x-6">
    <!-- Left: Cover Image -->
    <div class="w-32 h-48 bg-gray-200 dark:bg-gray-700 flex items-center justify-center rounded shadow-md overflow-hidden shrink-0">
      <img v-if="cover" :src="cover" class="w-full h-full object-cover" />
      <span v-else class="text-sm text-app-text-muted">No Cover</span>
    </div>

    <!-- Right: Metadata -->
    <div class="flex-1 space-y-3 min-w-0">
      <h2 class="font-bold truncate font-book" style="font-size: 2em;" :title="book.title">{{ book.title }}</h2>
      <div class="grid grid-cols-2 gap-4">
        <div class="text-app-text-muted mb-2 flex items-center gap-2">
          <span class="font-semibold text-app-text font-ui">Author:</span>
          <div class="flex flex-wrap gap-1 font-book">
            <span v-for="(author, i) in String(book.author || '').split(';').filter(a => a.trim() !== '')" :key="i" class="px-2 py-0.5 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 rounded-full" style="font-size: 0.85em;">
              {{ author.trim() }}
            </span>
          </div>
        </div>
        <p class="text-app-text-muted"><span class="font-semibold text-app-text font-ui">Publisher:</span> <span class="font-book">{{ book.publisher || 'Unknown' }}</span></p>
        <p class="text-app-text-muted"><span class="font-semibold text-app-text font-ui">ISBN:</span> <span class="font-book">{{ book.isbn || 'N/A' }}</span></p>
        <p class="text-app-text-muted"><span class="font-semibold text-app-text font-ui">Edition:</span> <span class="font-book">{{ book.edition || 'N/A' }}</span></p>
        <p class="text-app-text-muted col-span-2 truncate" :title="book.local_path">
          <span class="font-semibold text-app-text font-ui">Local Path:&nbsp;</span> 
          <a v-if="book.local_path" href="#" @click.prevent="openLocalPath" class="text-blue-500 hover:underline cursor-pointer font-book">{{ book.local_path }}</a>
          <span v-else class="font-book">Not set</span>
        </p>
      </div>
      <div class="mt-4 flex flex-col">
        <h3 class="font-semibold mb-2 text-app-text font-ui">Personal Notes</h3>
        <div 
          class="p-4 rounded bg-app-bg border border-app-border prose dark:prose-invert max-w-none break-words custom-prose font-book"
          v-html="renderedNotes"
        ></div>
      </div>
    </div>
  </div>
  <div v-else class="flex items-center justify-center w-full h-full text-app-text-muted text-lg">
    Select a book from the list to view its details
  </div>
</template>

<script setup lang="ts">
import { invoke } from '@tauri-apps/api/core';
import { computed } from 'vue';
import { marked } from 'marked';
import markedKatex from 'marked-katex-extension';
import DOMPurify from 'dompurify';
import 'katex/dist/katex.min.css';

marked.use(markedKatex({
  throwOnError: false,
  displayMode: true
}));

const props = defineProps<{ book: any, cover: string | null }>();

const renderedNotes = computed(() => {
  if (!props.book?.notes) return '<p class="text-app-text-muted italic">No notes available.</p>';
  // Parse markdown with KaTeX
  const rawHtml = marked.parse(props.book.notes) as string;
  // Sanitize, allowing MathML tags generated by KaTeX
  return DOMPurify.sanitize(rawHtml, {
    ADD_TAGS: ['math', 'annotation', 'semantics', 'mtext', 'mn', 'mo', 'mi', 'mspace', 'mover', 'munder', 'munderover', 'msup', 'msub', 'msubsup', 'mfrac', 'mroot', 'msqrt', 'mtable', 'mtr', 'mtd', 'mlabeledtr', 'mrow', 'menclose', 'mstyle', 'mpadded', 'mphantom', 'mglyph'],
    ADD_ATTR: ['display', 'mathvariant', 'mathsize', 'mathcolor', 'xmlns']
  });
});

const openLocalPath = async () => {
  if (props.book?.local_path) {
    try {
      await invoke('open_local_file', { path: props.book.local_path });
    } catch (error) {
      console.error('Failed to open file:', error);
      alert('Failed to open file: ' + error);
    }
  }
};
</script>